[catalouge]
172.31.26.73
172.31.26.24
172.31.26.23
172.31.26.33
172.31.26.45

[frontend]
172.31.27.57

[cart]
172.31.26.71

[local]
localhost

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar
; args we can pass varb 09 file refer and above lines for 8th file